In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
application_df = application_df.drop(columns = ['EIN', 'NAME', 'STATUS', 'SPECIAL_CONSIDERATIONS', 'ASK_AMT'])
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,INCOME_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,0,1
1,T3,Independent,C2000,Preservation,Co-operative,1-9999,1
2,T5,CompanySponsored,C3000,ProductDev,Association,0,0
3,T3,CompanySponsored,C2000,Preservation,Trust,10000-24999,1
4,T3,Independent,C1000,Heathcare,Trust,100000-499999,1
...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,0,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,0,0
34296,T3,CompanySponsored,C2000,Preservation,Association,0,0
34297,T5,Independent,C3000,ProductDev,Association,0,1
34298,T3,Independent,C1000,Preservation,Co-operative,1M-5M,0

In [3]:
application_df.nunique()

APPLICATION_TYPE    17
AFFILIATION          6
CLASSIFICATION      71
USE_CASE             5
ORGANIZATION         4
INCOME_AMT           9
IS_SUCCESSFUL        2
dtype: int64

In [4]:
application_type = application_df['APPLICATION_TYPE'].value_counts()
application_type

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type[application_type<500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [6]:
classification = application_df.CLASSIFICATION.value_counts()
classification

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: count, Length: 71, dtype: int64

In [7]:
classification_count = classification.loc[classification > 1]
classification_count

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list(classification[classification<500].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [9]:
categorical_numeric = pd.get_dummies(application_df)
categorical_numeric

,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,APPLICATION_TYPE_T7,APPLICATION_TYPE_T8,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,False,True,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
1,1,False,False,False,True,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,0,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
3,1,False,False,False,True,False,False,False,False,False,...,True,False,False,True,False,False,False,False,False,False
4,1,False,False,False,True,False,False,False,False,False,...,True,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,0,False,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34295,0,False,False,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34296,0,False,False,False,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34297,1,False,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,False
34298,0,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False

In [10]:
# Split our preprocessed data into our features and target arrays
y = categorical_numeric['IS_SUCCESSFUL'].values
X = categorical_numeric.drop(columns='IS_SUCCESSFUL').values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [50]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features= len(X_train[0])

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=20, input_dim = input_features, activation = "tanh"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=20, activation = "sigmoid"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="relu"))

# Check the structure of the model
nn.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_33 (Dense)            (None, 20)                820

 dense_34 (Dense)            (None, 20)                420

 dense_35 (Dense)            (None, 1)                 21

=================================================================
Total params: 1261 (4.93 KB)
Trainable params: 1261 (4.93 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [51]:
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [53]:
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 6s 8ms/step - loss: 0.5689 - accuracy: 0.7239
Epoch 2/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5590 - accuracy: 0.7263
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5567 - accuracy: 0.7289
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5545 - accuracy: 0.7292
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5593 - accuracy: 0.7259
Epoch 6/100
804/804 [==============================] - 5s 7ms/step - loss: 0.5534 - accuracy: 0.7293
Epoch 7/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5541 - accuracy: 0.7303
Epoch 8/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5568 - accuracy: 0.7285
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5583 - accuracy: 0.7301
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5539 - accuracy: 0.7313
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5519 - accuracy: 0.7327
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5521 - accuracy: 0.7317
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5506 - accuracy: 0.7300
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5635 - accuracy: 0.7221
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7309
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5856 - accuracy: 0.7194
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5777 - accuracy: 0.7116
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5599 - accuracy: 0.7289
Epoch 19/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5501 - accuracy: 0.7325
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5490 - accuracy: 0.7318
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7311
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7316
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7311
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5488 - accuracy: 0.7318
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5505 - accuracy: 0.7308
Epoch 26/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5490 - accuracy: 0.7314
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5534 - accuracy: 0.7322
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5527 - accuracy: 0.7315
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5483 - accuracy: 0.7315
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5492 - accuracy: 0.7325
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7317
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5582 - accuracy: 0.7307
Epoch 33/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5656 - accuracy: 0.7232
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5607 - accuracy: 0.7264
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5487 - accuracy: 0.7330
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7324
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5460 - accuracy: 0.7324
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7319
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5508 - accuracy: 0.7336
Epoch 40/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5531 - accuracy: 0.7307
Epoch 41/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5467 - accuracy: 0.7336
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5590 - accuracy: 0.7269
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5478 - accuracy: 0.7334
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7324
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7335
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5458 - accuracy: 0.7325
Epoch 47/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5465 - accuracy: 0.7327
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5471 - accuracy: 0.7329
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5481 - accuracy: 0.7331
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5486 - accuracy: 0.7336
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7339
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7340
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5519 - accuracy: 0.7324
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5473 - accuracy: 0.7331
Epoch 55/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5521 - accuracy: 0.7274
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5470 - accuracy: 0.7331
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7341
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7330
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7341
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5580 - accuracy: 0.7278
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5466 - accuracy: 0.7341
Epoch 62/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5448 - accuracy: 0.7339
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7341
Epoch 64/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5537 - accuracy: 0.7336
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7345
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7346
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5466 - accuracy: 0.7340
Epoch 68/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5452 - accuracy: 0.7341
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5444 - accuracy: 0.7335
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7347
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7339
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5445 - accuracy: 0.7349
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7350
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5474 - accuracy: 0.7344
Epoch 75/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5473 - accuracy: 0.7334
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5441 - accuracy: 0.7347
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7332
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5435 - accuracy: 0.7348
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7352
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5514 - accuracy: 0.7315
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7353
Epoch 82/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5442 - accuracy: 0.7336
Epoch 83/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5447 - accuracy: 0.7349
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5449 - accuracy: 0.7342
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7338
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7357
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5443 - accuracy: 0.7357
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7339
Epoch 89/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5444 - accuracy: 0.7352
Epoch 90/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5451 - accuracy: 0.7347
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7345
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5450 - accuracy: 0.7346
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5457 - accuracy: 0.7350
Epoch 94/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7352
Epoch 95/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5427 - accuracy: 0.7353
Epoch 96/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5434 - accuracy: 0.7364
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5431 - accuracy: 0.7340
Epoch 98/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5436 - accuracy: 0.7344
Epoch 99/100
804/804 [==============================] - 5s 6ms/step - loss: 0.5441 - accuracy: 0.7346
Epoch 100/100
804/804 [==============================] - 5s 7ms/step - loss: 0.5447 - accuracy: 0.7365

In [54]:
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5575 - accuracy: 0.7354 - 877ms/epoch - 3ms/step
Loss: 0.5574797987937927, Accuracy: 0.7353935837745667

In [55]:
filesave = r"C:\Users\alexi\Desktop\Starter_Code\AlphabetSoupCharity_Optimization.h5"
nn.save(filesave, save_format='hdf5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [ ]:
nn.save()